snapshot:
  url: https://raw.githubusercontent.com/commercialhaskell/stackage-snapshots/master/lts/22/43.yaml

packages:
  - lib/google-cloud-storage
  - lib/google-cloud-common
  - lib/google-cloud-compute
  - lib/google-cloud-logging
